In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_dataset=torchvision.datasets.MNIST(
root='.',
train=True,
transform=transforms.ToTensor(),
download=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw



In [3]:
train_dataset.data

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [4]:
train_dataset.data.max()

tensor(255, dtype=torch.uint8)

In [5]:
train_dataset.data.shape

torch.Size([60000, 28, 28])

In [6]:
train_dataset.targets

tensor([5, 0, 4,  ..., 5, 6, 8])

In [7]:
test_dataset=torchvision.datasets.MNIST(
root='.',
train=False,
transform=transforms.ToTensor(),
download=True)
test_dataset.data.shape

torch.Size([10000, 28, 28])

In [8]:
model=nn.Sequential(
nn.Linear(784,128),
nn.ReLU(),
nn.Linear(128,10)
)

In [9]:
device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
model.to(device)

cpu


Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=10, bias=True)
)

In [10]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters())

In [11]:
batch_size=128
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)
test_loader=torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)

In [12]:
#data loader puts the values between  0 and 1
tmp_loader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=1,shuffle=True)
for x,y in tmp_loader:
    print(x)
    print(x.shape)
    print(y.shape)
    break

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [13]:
train_dataset.transform(train_dataset.data.numpy()).max() #max tensor is 1

tensor(1.)

In [19]:
#Training model
n_epochs=10
train_losses=np.zeros(n_epochs)
test_losses=np.zeros(n_epochs)

for it in range(n_epochs):
    train_loss=[]
    for inputs,targets in train_loader:
        inputs,targets=inputs.to(device),targets.to(device) #sending to gpu
        inputs=inputs.view(-1,784) #reshaping the input
        optimizer.zero_grad()#zero the parameters 
        #forward pass
        outputs=model(inputs)
        loss=criterion(outputs,targets)
        #backward pass
        loss.backward()
        optimizer.step()
        
        train_loss.append(loss.item()) #the same for test
    test_loss=[]
    for inputs, targets in test_loader:
        inputs, targets=inputs.to(device),targets.to(device)
        inputs=inputs.view(-1,784)
        outputs=model(inputs)
        loss=criterion(outputs,targets)
        test_loss.append(loss.item())
    test_loss=np.mean(test_loss)
    
    #saving losses
    # train_losses[it]=train_loss
    test_losses[it]=test_loss
    print(f'Epoch {it+1}/{n_epochs},Test Loss:{test_loss:.4f}')

Epoch 1/10,Test Loss:0.0909
Epoch 2/10,Test Loss:0.0811
Epoch 3/10,Test Loss:0.0776
Epoch 4/10,Test Loss:0.0795
Epoch 5/10,Test Loss:0.0746
Epoch 6/10,Test Loss:0.0707
Epoch 7/10,Test Loss:0.0690
Epoch 8/10,Test Loss:0.0690
Epoch 9/10,Test Loss:0.0643
Epoch 10/10,Test Loss:0.0656
